# Generated by Django 4.2.5 on 2023-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripccion', models.CharField(default='Sin descripción', max_length=400)),
                ('precio', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
